name: Status Check

on:
  pull_request:
    branches:
      - main  # Adjust to your target branch

jobs:
  delayed-check:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Run the delay (sleep for 5 minutes)
    - name: Delay for 5 minutes
      run: sleep 300  # 300 seconds = 5 minutes

    # Run a simple status check (replace this with actual tests or commands)
    - name: Run status check
      run: echo "Status check complete after 5-minute delay."
